AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Serverless telegram bot to notifiy a telegram chat about cloudwatch events.
Resources:
  msgTelegramBot:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handler.msgTelegramBot
      Runtime: python3.6
      Description: An AWS Lambda function to dump cloudwatch events to telegram.
      MemorySize: 128
      Timeout: 300
      Environment:
        Variables: 
          TELEGRAM_TOKEN: '<YOUR:TELEGRAMTOKEN>'
          TELEGRAM_CHAT: '<YOURCHAT>'
      Events:
        Type: CloudWatchEvent
        Properties:
          Pattern:
            source: 
              - "aws.ec2"
            detail-type: 
              - "EC2 Instance State-change Notification"
